package com.myspace.project02;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Wealth implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Wealth() {
    }




}